---
# tasks file for automate_elasticsearch

  - name: Install elasticsearch
    include_tasks: install.yml
    when: elasticsearch_install 
    tag: install

  - name: Configure elasticsearch
    include_tasks: configure.yml
    when:  elasticsearch_configure
    tag: configure